# Generated by Django 3.1.1 on 2020-10-02 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateField()),
                ('name', models.CharField(default='Parkind Camera', max_length=100)),
                ('description', models.TextField(default='A camera connected to an IoT device that is connected to the Parkind system via its API')),
                ('video_height', models.IntegerField()),
                ('video_width', models.IntegerField()),
                ('video_fps', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('gpu_load', models.BooleanField(default=True)),
                ('top_statistic_tiles', models.BooleanField(default=True)),
                ('occupation_overview', models.BooleanField(default=True)),
                ('occupation_as_table', models.BooleanField(default=False)),
                ('gpu_usage_overview', models.BooleanField(default=True)),
                ('gpu_usage_as_table', models.BooleanField(default=False)),
                ('help_pane', models.BooleanField(default=True)),
                ('contribution_pane', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateField()),
                ('name', models.CharField(default='Parkind Device', max_length=100)),
                ('description', models.TextField(default='An IoT device connected to the Parkind system via its API')),
                ('request_logging', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingArea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.camera')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateField()),
                ('icon_bg_type', models.CharField(default='success', max_length=30)),
                ('icon_type', models.CharField(default='file', max_length=30)),
                ('message', models.CharField(default='Notification message content', max_length=100)),
                ('redirect_url', models.CharField(default='#', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceRequestHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('received_on', models.DateField()),
                ('request_code', models.CharField(max_length=30)),
                ('request_content', models.TextField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='parent_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device'),
        ),
    ]
