# Generated by Django 3.1.1 on 2020-10-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ip_address',
            field=models.CharField(default='255.255.255.255', max_length=16, unique=True),
        ),
    ]
