# Generated by Django 3.1.1 on 2020-09-22 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('gpu_load', models.BooleanField(default=True)),
                ('top_statistic_tiles', models.BooleanField(default=True)),
                ('occupation_overview', models.BooleanField(default=True)),
                ('occupation_as_table', models.BooleanField(default=False)),
                ('gpu_usage_overview', models.BooleanField(default=True)),
                ('gpu_usage_as_table', models.BooleanField(default=False)),
                ('help_pane', models.BooleanField(default=True)),
                ('contribution_pane', models.BooleanField(default=True)),
            ],
        ),
    ]
