# Generated by Django 3.1.1 on 2020-09-23 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ui', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateField()),
                ('name', models.CharField(default='Parkind Camera', max_length=100)),
                ('description', models.TextField(default='A camera connected to an IoT device that is connected to the Parkind system via its API')),
                ('video_height', models.IntegerField()),
                ('video_width', models.IntegerField()),
                ('video_fps', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateField()),
                ('name', models.CharField(default='Parkind Device', max_length=100)),
                ('description', models.TextField(default='An IoT device connected to the Parkind system via its API')),
                ('request_logging', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingArea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.camera')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceRequestHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('received_on', models.DateField()),
                ('request_code', models.CharField(max_length=30)),
                ('request_content', models.TextField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.device')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='parent_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.device'),
        ),
    ]
